/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TransactionId = IDL.Text;
export const BankAccount = IDL.Record({
  'ifsc' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'bankName' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const CoinBalance = IDL.Nat;
export const PhoneNumber = IDL.Text;
export const UserProfile = IDL.Record({
  'bankAccount' : IDL.Opt(BankAccount),
  'coinBalance' : CoinBalance,
  'phoneNumber' : PhoneNumber,
  'transactionHistory' : IDL.Vec(TransactionId),
});

export const idlService = IDL.Service({
  'addBankAccount' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'addFunds' : IDL.Func([TransactionId, IDL.Nat], [], []),
  'connectPhoneNumber' : IDL.Func([IDL.Text], [], []),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getBankAccount' : IDL.Func([], [IDL.Opt(BankAccount)], ['query']),
  'getCoinBalance' : IDL.Func([], [CoinBalance], ['query']),
  'getRewardTiers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
      ['query'],
    ),
  'getTransactionHistory' : IDL.Func([], [IDL.Vec(TransactionId)], ['query']),
  'getTransactionHistoryForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TransactionId)],
      ['query'],
    ),
  'isUserConnected' : IDL.Func([], [IDL.Bool], ['query']),
  'transferCoins' : IDL.Func([IDL.Principal, CoinBalance], [], []),
  'updatePhoneNumber' : IDL.Func([PhoneNumber], [IDL.Bool], []),
  'withdrawCoins' : IDL.Func([], [CoinBalance], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TransactionId = IDL.Text;
  const BankAccount = IDL.Record({
    'ifsc' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'bankName' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const CoinBalance = IDL.Nat;
  const PhoneNumber = IDL.Text;
  const UserProfile = IDL.Record({
    'bankAccount' : IDL.Opt(BankAccount),
    'coinBalance' : CoinBalance,
    'phoneNumber' : PhoneNumber,
    'transactionHistory' : IDL.Vec(TransactionId),
  });
  
  return IDL.Service({
    'addBankAccount' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addFunds' : IDL.Func([TransactionId, IDL.Nat], [], []),
    'connectPhoneNumber' : IDL.Func([IDL.Text], [], []),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getBankAccount' : IDL.Func([], [IDL.Opt(BankAccount)], ['query']),
    'getCoinBalance' : IDL.Func([], [CoinBalance], ['query']),
    'getRewardTiers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Nat))],
        ['query'],
      ),
    'getTransactionHistory' : IDL.Func([], [IDL.Vec(TransactionId)], ['query']),
    'getTransactionHistoryForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TransactionId)],
        ['query'],
      ),
    'isUserConnected' : IDL.Func([], [IDL.Bool], ['query']),
    'transferCoins' : IDL.Func([IDL.Principal, CoinBalance], [], []),
    'updatePhoneNumber' : IDL.Func([PhoneNumber], [IDL.Bool], []),
    'withdrawCoins' : IDL.Func([], [CoinBalance], []),
  });
};

export const init = ({ IDL }) => { return []; };