/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BankAccount {
  'ifsc' : string,
  'accountHolderName' : string,
  'bankName' : string,
  'accountNumber' : string,
}
export type CoinBalance = bigint;
export type PhoneNumber = string;
export type TransactionId = string;
export interface UserProfile {
  'bankAccount' : [] | [BankAccount],
  'coinBalance' : CoinBalance,
  'phoneNumber' : PhoneNumber,
  'transactionHistory' : Array<TransactionId>,
}
export interface _SERVICE {
  'addBankAccount' : ActorMethod<[string, string, string, string], undefined>,
  'addFunds' : ActorMethod<[TransactionId, bigint], undefined>,
  'connectPhoneNumber' : ActorMethod<[string], undefined>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getBankAccount' : ActorMethod<[], [] | [BankAccount]>,
  'getCoinBalance' : ActorMethod<[], CoinBalance>,
  'getRewardTiers' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getTransactionHistory' : ActorMethod<[], Array<TransactionId>>,
  'getTransactionHistoryForUser' : ActorMethod<
    [Principal],
    Array<TransactionId>
  >,
  'isUserConnected' : ActorMethod<[], boolean>,
  'transferCoins' : ActorMethod<[Principal, CoinBalance], undefined>,
  'updatePhoneNumber' : ActorMethod<[PhoneNumber], boolean>,
  'withdrawCoins' : ActorMethod<[], CoinBalance>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];