/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type PhoneNumber = string;
export interface BankAccount {
    ifsc: string;
    accountHolderName: string;
    bankName: string;
    accountNumber: string;
}
export type TransactionId = string;
export type CoinBalance = bigint;
export interface UserProfile {
    bankAccount?: BankAccount;
    coinBalance: CoinBalance;
    phoneNumber: PhoneNumber;
    transactionHistory: Array<TransactionId>;
}
export interface backendInterface {
    addBankAccount(accountHolderName: string, bankName: string, accountNumber: string, ifsc: string): Promise<void>;
    addFunds(transactionId: TransactionId, tier: bigint): Promise<void>;
    connectPhoneNumber(phoneNumber: string): Promise<void>;
    getAllUsers(): Promise<Array<[Principal, UserProfile]>>;
    getBankAccount(): Promise<BankAccount | null>;
    getCoinBalance(): Promise<CoinBalance>;
    getRewardTiers(): Promise<Array<[bigint, bigint]>>;
    getTransactionHistory(): Promise<Array<TransactionId>>;
    getTransactionHistoryForUser(user: Principal): Promise<Array<TransactionId>>;
    isUserConnected(): Promise<boolean>;
    transferCoins(toUser: Principal, amount: CoinBalance): Promise<void>;
    updatePhoneNumber(newPhoneNumber: PhoneNumber): Promise<boolean>;
    withdrawCoins(): Promise<CoinBalance>;
}
import type { BankAccount as _BankAccount, CoinBalance as _CoinBalance, PhoneNumber as _PhoneNumber, TransactionId as _TransactionId, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBankAccount(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBankAccount(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBankAccount(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addFunds(arg0: TransactionId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFunds(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFunds(arg0, arg1);
            return result;
        }
    }
    async connectPhoneNumber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.connectPhoneNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.connectPhoneNumber(arg0);
            return result;
        }
    }
    async getAllUsers(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBankAccount(): Promise<BankAccount | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankAccount();
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankAccount();
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoinBalance(): Promise<CoinBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoinBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoinBalance();
            return result;
        }
    }
    async getRewardTiers(): Promise<Array<[bigint, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRewardTiers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRewardTiers();
            return result;
        }
    }
    async getTransactionHistory(): Promise<Array<TransactionId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistory();
            return result;
        }
    }
    async getTransactionHistoryForUser(arg0: Principal): Promise<Array<TransactionId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionHistoryForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionHistoryForUser(arg0);
            return result;
        }
    }
    async isUserConnected(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isUserConnected();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isUserConnected();
            return result;
        }
    }
    async transferCoins(arg0: Principal, arg1: CoinBalance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.transferCoins(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transferCoins(arg0, arg1);
            return result;
        }
    }
    async updatePhoneNumber(arg0: PhoneNumber): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePhoneNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePhoneNumber(arg0);
            return result;
        }
    }
    async withdrawCoins(): Promise<CoinBalance> {
        if (this.processError) {
            try {
                const result = await this.actor.withdrawCoins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.withdrawCoins();
            return result;
        }
    }
}
function from_candid_UserProfile_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BankAccount]): BankAccount | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankAccount: [] | [_BankAccount];
    coinBalance: _CoinBalance;
    phoneNumber: _PhoneNumber;
    transactionHistory: Array<_TransactionId>;
}): {
    bankAccount?: BankAccount;
    coinBalance: CoinBalance;
    phoneNumber: PhoneNumber;
    transactionHistory: Array<TransactionId>;
} {
    return {
        bankAccount: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.bankAccount)),
        coinBalance: value.coinBalance,
        phoneNumber: value.phoneNumber,
        transactionHistory: value.transactionHistory
    };
}
function from_candid_tuple_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _UserProfile]): [Principal, UserProfile] {
    return [
        value[0],
        from_candid_UserProfile_n3(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _UserProfile]>): Array<[Principal, UserProfile]> {
    return value.map((x)=>from_candid_tuple_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
